### ISSUE TITLE
freshness-tracker should be able to read cluster bootstrap servers from burrow

### ISSUE THREAD

**Issue by jyates** [teslamotors/kafka-helmsman#30]
Burrow already exposes an endpoint to get cluster information (https://github.com/linkedin/Burrow/wiki/http-request-kafka-cluster-detail). We should able to use that to get the default bootstrap.servers for the cluster, rather than having to provide it as a config property. This only marginally helps us get around the rest of the config for things like SSL, but at least would help keep things consistent.

**Comment by raphaelauv** [comment]
hi , so freshness-tracker is not SSL compatible , no way to provide :
```java
properties.put("security.protocol", "SSL");
properties.put("ssl.key.password", "xxxxxxx");
properties.put("ssl.keystore.password", "xxxxxxx");
properties.put("ssl.keystore.location", "conf/xxxxxxx.jks");
```

thank you

**Comment by jyates** [comment]
hey @raphaelauv, thanks for giving it a try! We actually use freshness tracker with ssl. You just need to configure each cluster with Kafka security configs. For instance:
```
    clusters:
      - name: "fleet-analytics"
        numConsumers: 10
        kafka:
          bootstrap.servers: "my.cluster:9094"
          security.protocol: "SSL"
          ssl.keystore.location: "/etc/pki/kafka.keystore.jks"
          ssl.keystore.password: "KEYSTORE_PASSWORD"
          ssl.truststore.location: "/etc/pki/kafka.truststore.jks"
          ssl.truststore.password: "TRUSTSTORE_PASSWORD"
```

Unless you mean specifically SSL connections to burrow? Burrow is just exposed as a REST service, so we don't do any special connectivity there beyond simple GET requests.
