### ISSUE TITLE
Docker example of ConsumerFreshness_deploy

### ISSUE THREAD

**Issue by raphaelauv** [teslamotors/kafka-helmsman#36]
There go a very lazy docker example of ConsumerFreshness_deploy

```DockerFile
FROM openjdk:16-jdk-slim-buster
ADD ConsumerFreshness_deploy.jar ConsumerFreshness_deploy.jar
ADD conf.yaml conf.yaml
CMD java -jar ConsumerFreshness_deploy.jar --conf conf.yaml
```

```yaml
version: "3"
services:
  burrow:
    build:
      context: ./burrow/
      dockerfile: Dockerfile
    volumes:
      - ./burrow/burrow.toml:/etc/burrow/burrow.toml
    ports:
      - 8000:8000
    depends_on:
      - zookeeper
      - kafka

  time_lag:
    build:
      context: ./tesla/
      dockerfile: Dockerfile
    volumes:
      - ./tesla/conf.yaml:/conf.yaml
      - ./tesla/ConsumerFreshness_deploy.jar:/ConsumerFreshness_deploy.jar
    ports:
      - 8099:8081
    depends_on:
      - burrow
      - kafka
```

any suggestion is super welcome :+1:
